services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-go-api
    container_name: go-api
    ports:
      - "3000:3000" # Porta para acessar diretamente a API (opcional)
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80" # Porta para acessar o NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html # Diretório opcional para arquivos estáticos
    networks:
      - app-network

networks:
  app-network:
